"""add_plate_to_alerts_and_extend_zone_occupancy

Revision ID: 3a42e71bc020
Revises: f5a6b7c8d9e0
Create Date: 2026-04-11 11:54:29.348232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a42e71bc020'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - prune destructive drops and redundant columns."""
    # ### commands auto generated by Alembic - adjusted by Antigravity! ###
    
    # NOTE: alerts.plate_number already exists in the database but was missing from the ORM.
    # No op.add_column needed for alerts.
    
    # Add new columns to other tables
    op.add_column('vehicles', sa.Column('title', sa.String(length=50), nullable=False, server_default='Untitled'))
    op.add_column('zone_occupancy', sa.Column('zone_name', sa.String(length=100), nullable=True))
    op.add_column('zone_occupancy', sa.Column('floor', sa.String(length=50), nullable=True))
    
    # Remove the server_default after adding the column to title
    op.alter_column('vehicles', 'title', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone_occupancy', 'floor')
    op.drop_column('zone_occupancy', 'zone_name')
    op.drop_column('vehicles', 'title')
    # ### end Alembic commands ###
