"""drop system_config and camera_events

Revision ID: 3e94f140f526
Revises: 5c64d93ee242
Create Date: 2026-04-12 18:19:27.014723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3e94f140f526'
down_revision: Union[str, Sequence[str], None] = '5c64d93ee242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    
    op.drop_index(op.f('ix_camera_events_camera_id'), table_name='camera_events')
    op.drop_index(op.f('ix_camera_events_created_at'), table_name='camera_events')
    op.drop_index(op.f('ix_camera_events_event_type'), table_name='camera_events')
    op.drop_table('camera_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_events',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('device_serial', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('event_state', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('event_description', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('detection_target', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('trigger_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('snapshot_path', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_test', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__camera_e__3213E83F2E5E9B67'))
    )
    op.create_index(op.f('ix_camera_events_event_type'), 'camera_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_camera_events_created_at'), 'camera_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_camera_events_camera_id'), 'camera_events', ['camera_id'], unique=False)
    
    op.create_table('system_config',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=2048, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__system_c__3213E83FA57069EA'))
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    # ### end Alembic commands ###
